- name: "Modificando /etc/network/interfaces"
  ansible.builtin.template:
    src: etc/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify:
    - reboot
  